// Statik sahifalar (Qoidalar, Biz haqimizda) uchun tarjimalar
export const PAGE_STR = {
  uz: {
    back: "Orqaga",
    // Qoidalar
    termsTitle: "Foydalanish qoidalari",
    lastUpdated: "Oxirgi yangilanish: 2026-yil iyul",
    t1Title: "1. Platforma nimadan iborat",
    t1Body: "Uy24/7 — uy-joy egalari va ijarachilarni to'g'ridan-to'g'ri bog'laydigan platforma. Xizmat faqat ko'chmas mulk egalari (yoki ularning rasmiy vakillari) o'z e'lonlarini joylashi uchun mo'ljallangan. Rieltorlar, vositachilar yoki agentliklar tomonidan e'lon joylash taqiqlanadi.",
    t2Title: "2. E'lon joylash shartlari",
    t2Body: "E'lon joylayotgan foydalanuvchi mulkka egalik huquqini yoki uni ijaraga berish vakolatini tasdiqlaydi. Noto'g'ri, aldamchi yoki vositachilik maqsadida joylangan e'lonlar admin tomonidan ogohlantirishsiz o'chirilishi va akkaunt bloklanishi mumkin.",
    t3Title: "3. To'lovlar",
    t3Body: "\"Top e'lon\" xizmati orqali e'lonni qidiruv natijalarida yuqoriroq ko'rsatish pullik xizmat hisoblanadi. To'lovlar Payme yoki Click orqali amalga oshiriladi. To'langan xizmat muddati tugagach, e'lon oddiy tartibda ko'rsatiladi. Xizmat ko'rsatilgandan so'ng mablag' qaytarilmaydi.",
    t4Title: "4. Foydalanuvchi ma'lumotlari",
    t4Body: "Telefon raqami faqat identifikatsiya va bog'lanish maqsadida saqlanadi. Platforma foydalanuvchi raqamini uchinchi shaxslarga sotmaydi.",
    t5Title: "5. Javobgarlik",
    t5Body: "Platforma faqat egalar va ijarachilarni bog'lash vositasi bo'lib, tomonlar o'rtasidagi shartnoma, to'lov yoki nizolarga bevosita javobgar emas. Bitim shartlarini tekshirish tomonlarning o'z mas'uliyatidadir.",
    t6Title: "6. Aloqa",
    t6Body: "Savol va shikoyatlar uchun:",
    // Biz haqimizda
    aboutTitle: "Biz haqimizda",
    aboutIntro: "Uy24/7 — O'zbekistonda uy-joy ijarasini oddiy va ishonchli qiladigan platforma. Rieltorsiz — to'g'ridan-to'g'ri uy egasidan.",
    a1Title: "Muammo",
    a1Body: "Uy qidirayotgan odam ko'pincha bir xil e'lonni o'nlab rieltordan ko'radi, narx oshirib yuboriladi, va haqiqiy egasiga yetib borish qiyin bo'ladi.",
    a2Title: "Yechim",
    a2Body: "Bizda faqat uy egalari e'lon joylaydi. Har bir e'lon admin tomonidan tekshiriladi, telefon raqam tasdiqlanadi, shikoyat tizimi ishlaydi.",
    a3Title: "Qanday ishlaydi",
    a3Body: "Xaritadan yoki ro'yxatdan uy tanlang, egasi bilan ichki chat orqali bog'laning. Raqamingiz oshkor qilinmaydi. Kelishsangiz — to'g'ridan-to'g'ri uchrashasiz, hech qanday komissiya yo'q.",
    a4Title: "Bog'lanish",
    a4Body: "Savol, taklif yoki hamkorlik uchun:",
  },
  ru: {
    back: "Назад",
    termsTitle: "Правила пользования",
    lastUpdated: "Последнее обновление: июль 2026",
    t1Title: "1. О платформе",
    t1Body: "Uy24/7 — платформа, которая напрямую связывает владельцев жилья и арендаторов. Сервис предназначен только для размещения объявлений собственниками недвижимости (или их официальными представителями). Размещение объявлений риелторами, посредниками или агентствами запрещено.",
    t2Title: "2. Условия размещения объявлений",
    t2Body: "Размещая объявление, пользователь подтверждает право собственности или полномочия сдавать жильё в аренду. Ложные, вводящие в заблуждение или посреднические объявления могут быть удалены администратором без предупреждения, а аккаунт заблокирован.",
    t3Title: "3. Платежи",
    t3Body: "Услуга «Top объявление» — платное продвижение объявления выше в результатах поиска. Оплата производится через Payme или Click. По истечении оплаченного срока объявление показывается в обычном порядке. После оказания услуги средства не возвращаются.",
    t4Title: "4. Данные пользователей",
    t4Body: "Номер телефона хранится только для идентификации и связи. Платформа не продаёт номера пользователей третьим лицам.",
    t5Title: "5. Ответственность",
    t5Body: "Платформа является лишь средством связи между владельцами и арендаторами и не несёт прямой ответственности за договоры, платежи или споры между сторонами. Проверка условий сделки — ответственность самих сторон.",
    t6Title: "6. Контакты",
    t6Body: "По вопросам и жалобам:",
    aboutTitle: "О нас",
    aboutIntro: "Uy24/7 — платформа, которая делает аренду жилья в Узбекистане простой и надёжной. Без риелторов — напрямую от владельца.",
    a1Title: "Проблема",
    a1Body: "Человек, ищущий жильё, часто видит одно и то же объявление у десятков риелторов, цена накручивается, а добраться до настоящего владельца сложно.",
    a2Title: "Решение",
    a2Body: "У нас объявления размещают только владельцы. Каждое объявление проверяется администратором, номер телефона подтверждается, работает система жалоб.",
    a3Title: "Как это работает",
    a3Body: "Выберите жильё на карте или в списке, свяжитесь с владельцем через внутренний чат. Ваш номер не раскрывается. Договорились — встречаетесь напрямую, без всяких комиссий.",
    a4Title: "Связаться с нами",
    a4Body: "По вопросам, предложениям и сотрудничеству:",
  },
  en: {
    back: "Back",
    termsTitle: "Terms of Use",
    lastUpdated: "Last updated: July 2026",
    t1Title: "1. About the platform",
    t1Body: "Uy24/7 is a platform that connects property owners and renters directly. The service is intended only for property owners (or their official representatives) to post their own listings. Posting by realtors, intermediaries or agencies is prohibited.",
    t2Title: "2. Listing conditions",
    t2Body: "By posting a listing, the user confirms ownership of the property or authority to rent it out. False, misleading or intermediary listings may be removed by an admin without warning, and the account blocked.",
    t3Title: "3. Payments",
    t3Body: "The \"Boost\" service promotes a listing higher in search results for a fee. Payments are made via Payme or Click. Once the paid period ends, the listing returns to normal placement. Fees are non-refundable once the service has been delivered.",
    t4Title: "4. User data",
    t4Body: "Phone numbers are stored solely for identification and contact purposes. The platform does not sell user numbers to third parties.",
    t5Title: "5. Liability",
    t5Body: "The platform is only a means of connecting owners and renters, and bears no direct responsibility for agreements, payments or disputes between parties. Verifying the terms of any deal is the parties' own responsibility.",
    t6Title: "6. Contact",
    t6Body: "For questions and complaints:",
    aboutTitle: "About us",
    aboutIntro: "Uy24/7 is a platform that makes renting a home in Uzbekistan simple and trustworthy. No realtors — straight from the owner.",
    a1Title: "The problem",
    a1Body: "Someone looking for a home often sees the same listing from dozens of realtors, the price gets marked up, and reaching the actual owner is difficult.",
    a2Title: "The solution",
    a2Body: "Here only owners post listings. Every listing is reviewed by an admin, phone numbers are verified, and a reporting system is in place.",
    a3Title: "How it works",
    a3Body: "Pick a home from the map or the list, and contact the owner through the in-app chat. Your number stays private. Once you agree — you meet directly, with no commission.",
    a4Title: "Get in touch",
    a4Body: "For questions, suggestions and partnerships:",
  },
};

// Tanlangan tilni o'qish (asosiy ilova bilan bir xil manba)
export function getPageLang() {
  try {
    const saved = localStorage.getItem("uy247_lang");
    if (saved && PAGE_STR[saved]) return saved;
  } catch (_) {}
  return "uz";
}
